apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.number }}
      targetPort: {{ .Values.service.port.number }}
      protocol: TCP
      name: {{ .Values.service.port.name }}

  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
